apiVersion: spec.keptn.sh/0.2.3
kind: "Shipyard"
metadata:
  name: "rio-release-demo"
spec:
  stages:
    - name: dev
		sequences:
		-name: release
			tasks:
		- name: notify
		- name: deployment
		- name: test
		- name: evaluation
			properties:
				timeframe: "5m"
		- name: updateissue
	- name: production
		sequences:
		- name: release
			triggeredOn:
			- event: staging.release.finished
			tasks:
			- name: approval
				properties:
					pass: manual
					warning: manual
			- name: deployment
			- name: test
			- name: evaluation
				properties:
					timeframe: "5m"	
